"""S4 — 서빙 DB 스키마. SQLite / PostgreSQL(Supabase) 이중 백엔드.

[2026-08-18] SQLite -> PostgreSQL 이관.
  옮긴 이유는 무인 운영이다. GitHub Actions 는 잡이 끝나면 컨테이너가
  사라져 demo.db 가 증발한다. 매일 자동 적재를 하려면 DB 가 저장소 밖에
  있어야 한다. 인터넷·계정 없이도 로컬에서 돌아가야 하므로 SQLite 는
  폴백으로 남겼다 (config.DB_BACKEND 가 결정).

★ 설계에서 가장 중요한 제약
  demo/agents/ 는 PR #4 영역이라 수정할 수 없는데, 그 안에서
  con.execute("... WHERE farm_id=?", (fid,)) 처럼 SQLite 자리표시자 '?' 를 쓴다.
  PostgreSQL 은 '%s' 를 쓴다. 그래서 호출부를 고치는 대신, 여기 얇은
  커넥션 어댑터를 두고 '?' -> '%s' 로 번역한다. 결과적으로 agents/ ·
  advisor/ · daily_scoring 은 한 줄도 바뀌지 않는다.

★ 날짜를 DATE 가 아니라 TEXT 로 둔 이유
  advisor/recommend.py 와 agents/ 가 읽은 값에 곧바로
  datetime.strptime(date, "%Y-%m-%d") 를 건다. DATE 로 바꾸면 psycopg 가
  datetime.date 를 돌려줘 그 호출들이 전부 깨진다. 수정 금지 폴더가
  걸려 있으므로 컬럼 타입은 SQLite 시절 그대로 유지한다.
"""
from __future__ import annotations

import sqlite3

from config import DATABASE_URL, DB_BACKEND, DB_PATH

# ── 스키마 ────────────────────────────────────────────────────────
# 두 방언의 차이는 타입명과 자동증가 컬럼뿐이다. 컬럼 구성·PK 는 동일하다.
DDL_SQLITE = """
CREATE TABLE IF NOT EXISTS risk_calendar(
    date TEXT, block INT, risk_prob REAL, risk_grade TEXT,
    model_type TEXT, updated_at TEXT, PRIMARY KEY(date, block));
CREATE TABLE IF NOT EXISTS risk_hourly(
    date TEXT, hour INT, grp TEXT, risk_prob REAL, risk_grade TEXT,
    model_type TEXT, updated_at TEXT,
    PRIMARY KEY(date, hour, grp));
CREATE TABLE IF NOT EXISTS forecast_hourly(
    date TEXT, hour INT, wd REAL, ws REAL, sky TEXT, temp REAL, humid REAL,
    rain INT, source TEXT, updated_at TEXT,
    PRIMARY KEY(date, hour));
CREATE TABLE IF NOT EXISTS farm_config(
    farm_id TEXT PRIMARY KEY, name TEXT, lat REAL, lon REAL,
    facility_type TEXT, last_manure_removal_date TEXT);
CREATE TABLE IF NOT EXISTS receptor(
    farm_id TEXT, lat REAL, lon REAL, dist_m REAL, bearing REAL,
    use_code TEXT, virtual_phone TEXT, consent_yn INT);
CREATE TABLE IF NOT EXISTS notification_log(
    id INTEGER PRIMARY KEY, farm_id TEXT, work_type TEXT,
    sent_at TEXT, message TEXT, approved_yn INT);
"""

# receptor 에 PK 를 새로 만들지 않은 이유 — agents/notify_draft.py 가
#   "INSERT INTO receptor VALUES(?,?,?,?,?,?,?,?)" 로 컬럼 수를 8 로 못박아 뒀다.
#   id 컬럼을 추가하면 수정 금지 파일이 깨진다. FK 도 같은 이유로 안 건다.
DDL_POSTGRES = """
CREATE TABLE IF NOT EXISTS risk_calendar(
    date TEXT, block INTEGER, risk_prob DOUBLE PRECISION, risk_grade TEXT,
    model_type TEXT, updated_at TEXT, PRIMARY KEY(date, block));
CREATE TABLE IF NOT EXISTS risk_hourly(
    date TEXT, hour INTEGER, grp TEXT, risk_prob DOUBLE PRECISION, risk_grade TEXT,
    model_type TEXT, updated_at TEXT,
    PRIMARY KEY(date, hour, grp));
CREATE TABLE IF NOT EXISTS forecast_hourly(
    date TEXT, hour INTEGER, wd DOUBLE PRECISION, ws DOUBLE PRECISION, sky TEXT,
    temp DOUBLE PRECISION, humid DOUBLE PRECISION,
    rain INTEGER, source TEXT, updated_at TEXT,
    PRIMARY KEY(date, hour));
CREATE TABLE IF NOT EXISTS farm_config(
    farm_id TEXT PRIMARY KEY, name TEXT, lat DOUBLE PRECISION, lon DOUBLE PRECISION,
    facility_type TEXT, last_manure_removal_date TEXT);
CREATE TABLE IF NOT EXISTS receptor(
    farm_id TEXT, lat DOUBLE PRECISION, lon DOUBLE PRECISION,
    dist_m DOUBLE PRECISION, bearing DOUBLE PRECISION,
    use_code TEXT, virtual_phone TEXT, consent_yn INTEGER);
CREATE TABLE IF NOT EXISTS notification_log(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id TEXT, work_type TEXT,
    sent_at TEXT, message TEXT, approved_yn INTEGER);
"""

DDL = DDL_POSTGRES if DB_BACKEND == "postgres" else DDL_SQLITE

TABLES = ("risk_calendar", "risk_hourly", "forecast_hourly",
          "farm_config", "receptor", "notification_log")


# ── PostgreSQL 어댑터 ─────────────────────────────────────────────
def _translate(sql: str) -> str:
    """물음표 자리표시자를 psycopg 형식으로. 문자열 리터럴 안은 건드리지 않는다.

    psycopg 는 파라미터가 있을 때 퍼센트를 형식문자로 해석하므로 함께
    이스케이프한다. 이 함수는 파라미터가 있는 쿼리에만 쓴다.
    """
    out, in_str = [], False
    for ch in sql:
        if ch == "'":
            in_str = not in_str
            out.append(ch)
        elif in_str:
            out.append(ch)
        elif ch == "?":
            out.append("%s")
        elif ch == "%":
            out.append("%%")
        else:
            out.append(ch)
    return "".join(out)


def _clean(params):
    """numpy 스칼라를 파이썬 기본형으로. psycopg 에는 np.float64 어댑터가 없다."""
    if params is None:
        return None
    out = []
    for p in params:
        if type(p).__module__.split(".")[0] == "numpy" and hasattr(p, "item"):
            p = p.item()
        out.append(p)
    return tuple(out)


class _PgCursor:
    """psycopg 커서에 자리표시자 번역만 얹은 껍데기. 나머지는 그대로 위임."""

    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql, params=None):
        if params:
            self._raw.execute(_translate(sql), _clean(params))
        else:
            self._raw.execute(sql)
        return self

    def executemany(self, sql, seq):
        seq = [_clean(p) for p in seq]
        if seq:
            self._raw.executemany(_translate(sql), seq)
        return self

    def fetchone(self):
        return self._raw.fetchone()

    def fetchall(self):
        return self._raw.fetchall()

    def fetchmany(self, size=None):
        return self._raw.fetchmany(size) if size else self._raw.fetchmany()

    def close(self):
        self._raw.close()

    def __iter__(self):
        return iter(self._raw)

    @property
    def description(self):
        return self._raw.description

    @property
    def rowcount(self):
        return self._raw.rowcount


class PgConnection:
    """sqlite3.Connection 처럼 보이는 PostgreSQL 커넥션.

    sqlite3 는 Connection 에도 execute/executemany 가 있지만 psycopg 는
    커서에만 있다. 호출부(특히 수정 금지인 agents/)가 con.execute(...) 를
    쓰므로 여기서 메꾼다.
    """

    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql, params=None):
        return _PgCursor(self._raw.cursor()).execute(sql, params)

    def executemany(self, sql, seq):
        return _PgCursor(self._raw.cursor()).executemany(sql, seq)

    def executescript(self, sql: str):
        """sqlite3 전용 메서드의 대체. psycopg 는 파라미터 없는 다중문을 허용한다."""
        with self._raw.cursor() as cur:
            cur.execute(sql)
        self._raw.commit()
        return self

    def cursor(self):
        return _PgCursor(self._raw.cursor())

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        if exc[0] is None:
            self._raw.commit()
        else:
            self._raw.rollback()
        return False


_PG_DDL_DONE = False


def _connect_postgres() -> PgConnection:
    global _PG_DDL_DONE
    import psycopg     # requirements: psycopg[binary]

    # prepare_threshold=None 이 필요한 이유 — Supabase 의 트랜잭션 풀러(pgbouncer,
    #   6543 포트)는 서버측 prepared statement 를 지원하지 않는다. psycopg3 는
    #   같은 쿼리를 5회 실행하면 자동으로 prepare 로 바꾸므로, 끄지 않으면
    #   매일 잘 돌던 잡이 어느 순간 DuplicatePreparedStatement 로 죽는다.
    con = psycopg.connect(DATABASE_URL, prepare_threshold=None,
                          connect_timeout=15,
                          application_name="smart-livestock-ai")
    wrapped = PgConnection(con)
    if not _PG_DDL_DONE:
        wrapped.executescript(DDL_POSTGRES)   # CREATE TABLE IF NOT EXISTS 라 멱등
        _PG_DDL_DONE = True
    return wrapped


def connect():
    """백엔드에 맞는 커넥션을 돌려준다. 호출부는 어느 쪽인지 몰라도 된다."""
    if DB_BACKEND == "postgres":
        return _connect_postgres()
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(DB_PATH)
    con.executescript(DDL_SQLITE)
    return con


def backend() -> str:
    return DB_BACKEND


def describe() -> str:
    """로그용 한 줄. 접속 문자열의 비밀번호는 절대 찍지 않는다."""
    if DB_BACKEND != "postgres":
        return f"SQLite {DB_PATH}"
    host = DATABASE_URL.rsplit("@", 1)[-1] if "@" in DATABASE_URL else "?"
    return f"PostgreSQL {host}"


def primary_key_columns(con, table: str) -> list[str]:
    """PK 컬럼명을 순서대로. run_check 의 스키마 검증이 쓴다 (백엔드 중립)."""
    if DB_BACKEND == "postgres":
        rows = con.execute(
            "SELECT a.attname FROM pg_index i "
            "JOIN pg_attribute a ON a.attrelid = i.indrelid "
            "                   AND a.attnum = ANY(i.indkey) "
            "WHERE i.indrelid = ?::regclass AND i.indisprimary "
            "ORDER BY array_position(i.indkey, a.attnum)", (table,)).fetchall()
        return [r[0] for r in rows]
    rows = con.execute(f"PRAGMA table_info({table})").fetchall()
    return [r[1] for r in sorted((r for r in rows if r[5]), key=lambda r: r[5])]


def fetch_frame(con, sql: str, params=None):
    """SELECT 결과를 DataFrame 으로. pandas.read_sql 은 백엔드마다 경고가 달라 직접 만든다."""
    import pandas as pd
    cur = con.execute(sql, params) if params else con.execute(sql)
    rows = cur.fetchall()
    cols = [c[0] for c in cur.description]
    return pd.DataFrame(rows, columns=cols)


# ── upsert ────────────────────────────────────────────────────────
# 아래 SQL 은 SQLite(3.24+) 와 PostgreSQL 양쪽에서 그대로 동작한다.
# 자리표시자만 어댑터가 번역한다.

def upsert_risk_legacy(con, rows: list[tuple]) -> None:
    """rows: (date, block, risk_prob, risk_grade, model_type, updated_at)"""
    con.executemany(
        "INSERT INTO risk_calendar(date, block, risk_prob, risk_grade, model_type, updated_at) "
        "VALUES(?,?,?,?,?,?) ON CONFLICT(date, block) DO UPDATE SET "
        "risk_prob=excluded.risk_prob, risk_grade=excluded.risk_grade, "
        "model_type=excluded.model_type, updated_at=excluded.updated_at",
        rows,
    )
    con.commit()


def upsert_risk(con, rows: list[tuple]) -> None:
    """rows: (date, hour, grp, risk_prob, risk_grade, model_type, updated_at)

    ★ 기존 risk_calendar 는 PRIMARY KEY(date, block) 이라 그룹을 도입하면
      뒤 행이 앞 행을 조용히 덮어쓴다. 그래서 별도 테이블을 쓴다.
      grp 인 이유 — group 은 SQL 예약어라 컬럼명으로 못 쓴다.
    """
    con.executemany(
        "INSERT INTO risk_hourly(date, hour, grp, risk_prob, risk_grade, "
        "model_type, updated_at) VALUES(?,?,?,?,?,?,?) "
        "ON CONFLICT(date, hour, grp) DO UPDATE SET "
        "risk_prob=excluded.risk_prob, risk_grade=excluded.risk_grade, "
        "model_type=excluded.model_type, updated_at=excluded.updated_at",
        rows,
    )
    con.commit()


def upsert_forecast(con, rows: list[tuple]) -> None:
    """rows: (date, hour, wd, ws, sky, temp, humid, rain, source, updated_at)

    s5 의 플룸 그룹 선택이 시각별 바람을 필요로 한다. risk_hourly 에는
    확률만 있으므로 예보 원값을 따로 남긴다 (재호출 방지).
    """
    con.executemany(
        "INSERT INTO forecast_hourly(date, hour, wd, ws, sky, temp, humid, "
        "rain, source, updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) "
        "ON CONFLICT(date, hour) DO UPDATE SET "
        "wd=excluded.wd, ws=excluded.ws, sky=excluded.sky, temp=excluded.temp, "
        "humid=excluded.humid, rain=excluded.rain, source=excluded.source, "
        "updated_at=excluded.updated_at",
        rows,
    )
    con.commit()


def upsert_farm(con, farm: dict) -> None:
    # 구버전은 INSERT OR REPLACE 였다. PostgreSQL 에 없는 문법이라
    # 양쪽에서 동작하는 ON CONFLICT DO UPDATE 로 바꿨다.
    con.execute(
        "INSERT INTO farm_config(farm_id, name, lat, lon, facility_type, "
        "last_manure_removal_date) VALUES(?,?,?,?,?,?) "
        "ON CONFLICT(farm_id) DO UPDATE SET "
        "name=excluded.name, lat=excluded.lat, lon=excluded.lon, "
        "facility_type=excluded.facility_type, "
        "last_manure_removal_date=excluded.last_manure_removal_date",
        (farm["farm_id"], farm["name"], farm["lat"], farm["lon"],
         farm["facility_type"], farm["last_manure_removal_date"]),
    )
    con.commit()
